### ISSUE TITLE
hello，I want to ask how to download the video on VIKI.

### ISSUE THREAD

**Issue by ali617768987** [sohail0098/Viki-Subs-Downloader#1]
Excuse me, do you know how to download the videos on VIKI?

**Comment by sohail0098** [comment]
This current script is actually a stripped version of the video downloader I wrote long ago. But all the videos fetched using this method are DRM protected so this doesn't work anymore (except for grabbing subtitles of course). 

As for working downloader, check out [yt-dlp](https://github.com/yt-dlp/yt-dlp)
I am trying to figure out the mobile API calls so I can create a lightweight version of it.

**Comment by ali617768987** [comment]
> This current script is actually a stripped version of the video downloader I wrote long ago. But all the videos fetched using this method are DRM protected so this doesn't work anymore (except for grabbing subtitles of course).
> 
> As for working downloader, check out [yt-dlp](https://github.com/yt-dlp/yt-dlp)
> I am trying to figure out the mobile API calls so I can create a lightweight version of it.

Ok, thank you for your answer, waiting for the version you made ~
