### ISSUE TITLE
what's the problem 

### ISSUE THREAD

**Issue by REDAKUN** [sohail0098/Viki-Subs-Downloader#2]
what's the problem : 

![image_2021-09-06_10-30-26](https://user-images.githubusercontent.com/68442725/132142023-80a39add-88dd-407d-b0b6-42629f3195d0.png)

![image_2021-09-06_10-29-21](https://user-images.githubusercontent.com/68442725/132142026-245c4374-da5a-41bb-b204-412c04ca11c6.png)
 here are my cookies : https://pastebin.com/kAgEsLyL

**Comment by sohail0098** [comment]
I am not sure. I just traveled to a different country so I don't have my device with me. I'll check it up later on a friend's pc. 

Meanwhile, can you show you how you added the cookie in the py script? Maybe you added some extra quote? Or maybe it's wrong of me to add cookie by that method. I'll need to try later.

**Comment by sohail0098** [comment]
Fixed. Please try now. Also your cookie is probably not viki pass subscribed so it won't get subs from those kind of content which is behind viki pass.

**Comment by REDAKUN** [comment]
I'll try later thanks and no ihave viki pass plus account not free as u said
