### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by liongtwap** [sohail0098/Viki-Subs-Downloader#3]
Hi, please help, It can not download from this =
https://www.viki.com/tv/36684c-mirror-a-tale-of-twin-cities
https://www.viki.com/tv/21864c-chinese-paladin-5-clouds-of-the-world

Please add a choice to download languange subtitle : i.e., just download polish subtitles only

thanks a lot

**Comment by sohail0098** [comment]
Hi. I've added a quick fix for the shows with some special characters which cannot be kept in folder names. 
https://github.com/sohail0098/Viki-Subs-Downloader/commit/82fe0e266ac9fb8477b257a7ca73de652dd9fd5d
As for the language selection, I'll re-write this script in a better way later (possibly with an option for non-DRM video download).

The current script was written very leniently. It crashes when subs cannot be found or if episodes are locked behind subscription restrictions or something.
